### ISSUE TITLE
Environmental Property Term: Evaporation

### ISSUE THREAD

**Issue by ashleysommer** [CSIRO-enviro-informatics/vocab-content#4]
### Add a new term
http://registry.it.csiro.au/def/environment/property/evaporation

I was using [Evapotranspiration](http://registry.it.csiro.au/sandbox/csiro/oznome/AWRA-L/evapotranspiration) for this, but that is not correct.

From: http://www.bom.gov.au/watl/eto/about.shtml
> "Evaporation is not the same as evapotranspiration"

SILO weather stations API provides actual "Class A Evaporation" values, in millimeters.
Evaporation as a property is not defined in any registry that I've searched across. 

https://www.longpaddock.qld.gov.au/silo/data_format.html

**Comment by dr-shorthair** [comment]
Do #8 first?

**Comment by dr-shorthair** [comment]
I found a definition here: http://www.bom.gov.au/watl/evaporation/ 

"Evaporation is the amount of water which evaporates from an open pan called a Class A evaporation pan. The rate of evaporation depends on factors such as cloudiness, air temperature and wind speed. Measurements are made by the addition or subtraction of a known amount of water, which then tells us how much water has evaporated from the pan."

**Comment by dr-shorthair** [comment]
http://registry.it.csiro.au/sandbox/environment/property/evaporation ?

**Comment by jyucsiro** [comment]
Would adding some general notion of evaporation be helpful also? e.g. from https://water.usgs.gov/edu/watercycleevaporation.html
"Evaporation is the process by which water changes from a liquid to a gas or vapor. Evaporation is the primary pathway that water moves from the liquid state back into the water cycle as atmospheric water vapor."

**Comment by dr-shorthair** [comment]
I see why you might suggest that. 
But I think that the general concept 'evaporation' is probably a physical process. 
The vocabulary is of what QUDT calls 'quantity kinds' which have a defined dimensionality which can then be matched with a suitable uom, so not clear that a physical process definition belongs?
