### ISSUE TITLE
Environmental Property Term: Soil Temperature

### ISSUE THREAD

**Issue by ashleysommer** [CSIRO-enviro-informatics/vocab-content#5]
### Add a new term

http://registry.it.csiro.au/def/environment/property/soil_temperature

This will be very similar in definition to the existing [Water Temperature](http://registry.it.csiro.au/def/environment/property/water_temperature) property.

As with Water Temperature, this is a specialisation of [ThermodynamicTemerature](http://registry.it.csiro.au/?entity=http%3a%2f%2fqudt.org%2fvocab%2fquantity%23ThermodynamicTemperature)

DAFWA Weather stations API reports daily Soil Temperature in degrees Celsius.

This is not the same as Air Temperature or Water Temperature, and should have its own term defined.

**Comment by dr-shorthair** [comment]
Do #8 first?

**Comment by dr-shorthair** [comment]
http://registry.it.csiro.au/sandbox/environment/property/soil_temperature ?
