### ISSUE TITLE
Environmental Property Term: Atmospheric water vapour pressure

### ISSUE THREAD

**Issue by ashleysommer** [CSIRO-enviro-informatics/vocab-content#6]
### Add a new term

http://registry.it.csiro.au/def/environment/property/vapour_pressure

This is related to, but different from the [atmospheric pressure](http://registry.it.csiro.au/def/qudt/1.1/qudt-quantity/AtmosphericPressure) property.

SILO Weather stations API reports daily Atmospheric Water Vapour Pressure in degrees HectoPascals.

https://en.wikipedia.org/wiki/Vapor_pressure
https://www.physicsforums.com/threads/vapor-pressure-and-atmospheric-pressure.699185/
https://www.longpaddock.qld.gov.au/silo/data_format.html

**Comment by dr-shorthair** [comment]
Do #8 first?

**Comment by dr-shorthair** [comment]
This appears to be the key point: 
https://en.wikipedia.org/wiki/Vapor_pressure#Meaning_in_meteorology

**Comment by dr-shorthair** [comment]
hPa is equivalent to mBar. 
I've made a pull-request to QUDT to add hPa to their vocabulary, but meanwhile have put both in the proposed definition. 
http://registry.it.csiro.au/sandbox/environment/property/vapour_pressure

**Comment by dr-shorthair** [comment]
Now I'm going to build some forms so you can do this for yourself!

**Comment by ashleysommer** [comment]
@dr-shorthair 
Im using http://environment.data.gov.au/def/unit/HectoPascal as unit for now, though it would certainly be great to have it in QUDT.

As for a form, while convenient, that is not the reason that I didn't add these terms myself. I know how to write RDF+XML documents with the required metadata to insert a new registry term. The reason these proposals were created was to encourage the formal process around adding new terms to the registry.

**Comment by dr-shorthair** [comment]
Yes - good to exercise the process. 
However, would also be good to have a form - I would prefer it myself anyway. 
I'm suggesting that for some contributors, the process could involve use of the sandbox.

**Comment by dr-shorthair** [comment]
See http://registry.it.csiro.au/sandbox/environment/property/_vapour_pressure
